name: RealEstate
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7160931241232902
title: Homes for Sale and Home to Buy
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.8588860500603914
  lightness: 0.5381732378154993
  saturation: 0.8112050821073353
  rhythmicContrast: 0.6760801589116454
purpose: []
